# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRTC-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTC-sample
  pod 'Firebase/Firestore'
  pod 'GoogleWebRTC'


  target 'WebRTC-sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebRTC-sampleUITests' do
    # Pods for testing
  end

end
